version: '3.8'
services:
  db:
   image: postgres
   restart: always
   container_name: postgres_notedb
   environment:
     POSTGRES_PASSWORD: admin
     POSTGRES_DB: notedb
   ports:
     - "5432:5432"
   volumes:
    - postgres_notedata:/var/lib/postgresql/data	
volumes:
  postgres_notedata: